### ISSUE TITLE
Inquiry about the code release for your paper

### ISSUE THREAD

**Issue by Meeilwin** [Nauhcnay/Deep-Sketch-Vectorization#1]
Hi, I hope you're doing well! I recently read your paper "Deep Sketch Vectorization via Implicit Surface Extraction" from SIGGRAPH 2024 and found it very interesting, especially the way you handle complex sketches with your novel approach.
I’m a student working on sketch processing, and your method seems like a valuable tool that could benefit my research. I noticed the code hasn’t been released yet, so I wanted to ask if there’s any timeline for when it might be available?
Thanks a lot for your time, and I look forward to hearing from you!
Best regards,
Meeilwin

**Comment by Nauhcnay** [comment]
Hi, Thanks for the code request and sorry for the late response, I just updated this repository. Let me know if there is anything that not clear.

**Comment by Meeilwin** [comment]
Thanks for sharing!
